<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Implementation of the Open Charge Point Protocol (OCPP).</Description>
    <PackageTags>ocpp;ocpp-j;ocpp-json;websockets;e-mobility</PackageTags>
    <Version>1.0.2</Version>
    <Authors>fabyr and contributors</Authors>
    <AssemblyName>OcppSharp</AssemblyName>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/fabyr/ocpp-sharp</RepositoryUrl>
    <PackageProjectUrl>https://github.com/fabyr/ocpp-sharp</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <RootNamespace>OcppSharp</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)\..\README.md" Pack="true" PackagePath="\" />
    <None Include="$(MSBuildProjectDirectory)\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.0" />
  </ItemGroup>

</Project>
